### PR TITLE
ext/psu update and recs

### PR DESCRIPTION
**Pull request by KipOmaha**
Could you add a part, "Creating Extensions and Psuedos" than I was thinking you should get into the built in extensions `template` and `attr` and entitle it built in extensions.
Which is basically what it is already it's just giving it different headings and adding a part on other ways to interface with the `extensions` and `pseudo` `API`

### CODE REVIEW

**Comment by csuwildcat** [comment]
Like most of the changes and the callout of making the sections clearer about Pseudos/Extensions. On the latter one, maybe we just unify them into one section, with a subsection on doing custom ones? I think that might be better than maintaining one. Thoughts?

**Comment by KipOmaha** [comment]
I don't disagree, on unifying them since the psuedos compliment the extensions so well. I need to get to my computer at home, i left a couple notes on it, I,ll get back to you on it.

**Comment by KipOmaha** [comment]
I will be working on this tonight @csuwildcat

**Comment by KipOmaha** [comment]
Committed a stylesheet change for the landing page to this PR

**Comment by KipOmaha** [comment]
Update on thread: 

The `Git Projects` feature could be a good place to put the alpha builds project milestones.  
Especially for enhancements and current bugs. I will also create a commit with a change to the landing page where the text `warning` will link to the projects tab of the core-2 repo.

**Comment by KipOmaha** [comment]
Closing this cause I started a new pull request with all the changes for the docs.

**Pull request closed without merging**
